language: node_js
node_js:
    - "node"
notifications:
    -  email: false
services:
    - postgresql
before_script:
    - psql -c 'create database littlewindowtest;' -U postgres
script:
  - npm test
  - cd client && npm test
